### ISSUE TITLE
Can you give the link to the preprocessed [CelebA]

### ISSUE THREAD

**Issue by sulei95** [DetionDX/Attribute2Sketch2Face#2]
In the README.md, you have put the link to LFW; but you forgot the link to CelebA. So can you handle it?

**Comment by xingdi1990** [comment]
@sulei95 I would like to give the link to CelebA later. BTW, did you run the code on LFW? How does it work?

**Comment by sulei95** [comment]
@DetionDX Thank you for your reply. But I haven't run the code yet.
